/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbn;
import BUS.BENHNHANBUS;
import DAO.BENHNHAN;
import DAO.THUOC;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tien Nguyen
 */
public class TimXoaSua extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    BENHNHANBUS bnbus=new BENHNHANBUS();
    List<BENHNHAN> list= new ArrayList();
    List<BENHNHAN> list_xoa = new ArrayList();
    
    public TimXoaSua() {
        initComponents();
        Laydanhsach();
    }
     public void Laydanhsach()
    {
         try {
            
            
            list= bnbus.Laydanhsachbenhnhan();
            
            DefaultTableModel model = (DefaultTableModel) grBenhNhan.getModel();
            
            for(int i=0;i<list.size();i++)
            {
                String LoaiThuoc = "";
                int SoLuong = 0;
                if (list.get(i).getDanhSachThuoc().size() != 0)
                {
                    for (THUOC t:list.get(i).getDanhSachThuoc())
                    {
                        LoaiThuoc +=  t.getMALOAITHUOC().replace(" ","") + ", ";
                        System.out.println(LoaiThuoc);
                        SoLuong += t.getSOLUONG();
                    }
                }
                // Xóa đi 2 kí tự dư cuối
            if (LoaiThuoc.length() > 0)
            {
                LoaiThuoc = LoaiThuoc.substring(0, LoaiThuoc.length() - 2);
            }
            model.addRow(new Object[]{list.get(i).getMABN(),list.get(i).getTENBN(),
                list.get(i).getTUOI(),list.get(i).getDIACHI(),list.get(i).getGIOITINH(),
                list.get(i).getLOAIBN(), list.get(i).getCANNANG(),LoaiThuoc, SoLuong});
            }
       
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhanMem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grBenhNhan = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSava = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÝ BỆNH NHÂN LAO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhanMem.setBackground(new java.awt.Color(0, 204, 204));
        txtPhanMem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPhanMem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPhanMem.setText("TÌM KIẾM - SỬA - XOÁ THÔNG TIN BỆNH NHÂN");
        getContentPane().add(txtPhanMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 13, 634, 43));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 140, 278, 34));

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setBorder(null);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 139, 110, 34));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/sign-add-icon.png"))); // NOI18N
        btnThem.setText("Thêm Mới");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, 40));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/xoa.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 100, 40));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/i5.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 100, 40));

        btnXuatExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/excel.png"))); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.setBorder(null);
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 77, 109, 44));

        grBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ BN", "TÊN BN", "TUỔI", "ĐỊA CHỈ", "GIỚI TÍNH", "LOẠI BN", "CÂN NẶNG", "LOẠI THUỐC", "SỐ LƯỢNG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        grBenhNhan.setFillsViewportHeight(true);
        grBenhNhan.setFocusCycleRoot(true);
        grBenhNhan.setFocusTraversalPolicyProvider(true);
        grBenhNhan.setInheritsPopupMenu(true);
        grBenhNhan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grBenhNhan.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(grBenhNhan);
        grBenhNhan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (grBenhNhan.getColumnModel().getColumnCount() > 0) {
            grBenhNhan.getColumnModel().getColumn(0).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(0).setPreferredWidth(10);
            grBenhNhan.getColumnModel().getColumn(2).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(2).setPreferredWidth(10);
        }
        grBenhNhan.getAccessibleContext().setAccessibleName("");
        grBenhNhan.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, 1230, 387));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconBack.png"))); // NOI18N
        btnBack.setText("Trở Về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 40));

        btnSava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconSave.png"))); // NOI18N
        btnSava.setText("Lưu");
        btnSava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSava, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 100, 40));

        btnUndo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconUndo.png"))); // NOI18N
        btnUndo.setText("Phục Hồi");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/gdtimkiem.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Them a = new Them();
        a.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int index = grBenhNhan.getSelectedRow();
        System.out.println("\n");
        System.out.println(index);
            
        Sua frm = new Sua(list.get(index));
        frm.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        XuatExcel frm = new XuatExcel();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String tim = txtTimKiem.getText();
        //            List<BENHNHAN> list_tmp= bnbus.Timkiembenhnhan(txtTimKiem.getText().toString());
        List<BENHNHAN> list_tmp= new ArrayList();
        for (BENHNHAN b : list)
            if (b.getTENBN().indexOf(tim) != -1)
            {
                System.out.println(b.getTENBN());
                list_tmp.add(b);
            }
        DefaultTableModel model = (DefaultTableModel) grBenhNhan.getModel();
        while(model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        System.out.println(model.getRowCount());
        for(int i=0;i<list_tmp.size();i++)
        {
            String LoaiThuoc = "";
            int SoLuong = 0;
            for (THUOC t:list_tmp.get(i).getDanhSachThuoc())
            {
                LoaiThuoc += "\n" +  t.getMALOAITHUOC();
                SoLuong += t.getSOLUONG();
            }
            System.out.println(list_tmp.get(i).getTENBN());
            model.addRow(new Object[]{list_tmp.get(i).getMABN(),list_tmp.get(i).getTENBN(),
                list_tmp.get(i).getTUOI(),list_tmp.get(i).getDIACHI(),list_tmp.get(i).getGIOITINH(),
                list_tmp.get(i).getLOAIBN(), list_tmp.get(i).getCANNANG(),LoaiThuoc, SoLuong});
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Main_1 a = new Main_1();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavaActionPerformed
        // TODO add your handling code here:
        // Lưu - duyệt xóa các bệnh nhân trong list xóa
        for(BENHNHAN bn:list_xoa)
        {
            try {
                bnbus.xoabenhnhan(bn);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TimXoaSua.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TimXoaSua.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnSavaActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        // Xóa toàn bộ view
        DefaultTableModel model = (DefaultTableModel) grBenhNhan.getModel();
        while(model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        // Load lại từ database
        Laydanhsach();
        
        // Gán lại list_xoa bằng rổng
        list_xoa.clear();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel) grBenhNhan.getModel();
            int index = grBenhNhan.getSelectedRow();
            System.out.println("\n");
            System.out.println(index);
            
            // Xóa khỏi view
            model.removeRow(index);
            
            // Đưa vào list xóa
            list_xoa.add(list.get(index));
            
            // Xóa ra khỏi list bệnh nhân
            list.remove(index);
            System.out.println (list.size());
            
        } catch (ArrayIndexOutOfBoundsException ex)
        {
            System.out.println("Lỗi chưa lựa chọn gì, bỏ qua");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           // java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
           // java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
           // java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TimXoaSua().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSava;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JTable grBenhNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtPhanMem;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
