/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbn;

import BUS.BENHNHANBUS;
import DAO.BENHNHAN;
import DAO.THUOC;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tien Nguyen
 */
public class XuatExcel extends javax.swing.JFrame {

    /**
     * Creates new form XuatExcel
     */
    
     BENHNHANBUS bnbus=new BENHNHANBUS();
    List<BENHNHAN> list= new ArrayList();
    public XuatExcel() {
        initComponents();
        Laydanhsach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhanMem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grBenhNhan = new javax.swing.JTable();
        btnXuatExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhanMem.setBackground(new java.awt.Color(0, 204, 204));
        txtPhanMem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPhanMem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPhanMem.setText("Trạm Y Tế Xã Khánh Hoà");
        getContentPane().add(txtPhanMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 240, 31));

        grBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MABN", "TENBN", "TUỔI", "DIACHI", "GIOITINH", "LOAIBN", "SOKY", "LOẠI THUỐC", "SOLUONG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        grBenhNhan.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(grBenhNhan);
        grBenhNhan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (grBenhNhan.getColumnModel().getColumnCount() > 0) {
            grBenhNhan.getColumnModel().getColumn(0).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(0).setPreferredWidth(10);
            grBenhNhan.getColumnModel().getColumn(2).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(2).setPreferredWidth(25);
            grBenhNhan.getColumnModel().getColumn(3).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(3).setPreferredWidth(40);
            grBenhNhan.getColumnModel().getColumn(4).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(4).setPreferredWidth(10);
            grBenhNhan.getColumnModel().getColumn(6).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(6).setPreferredWidth(10);
            grBenhNhan.getColumnModel().getColumn(8).setResizable(false);
            grBenhNhan.getColumnModel().getColumn(8).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, 1160, 460));

        btnXuatExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/excel.png"))); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.setBorder(null);
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BẢNG QUYẾT TOÁN THUỐC LAO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 11, 377, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ngày..........Tháng............Năm............");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 65, 228, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Trung Tâm Y Tế Huyện Châu Phú");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 360, 31));

        jLabel4.setText("--------------------------------------------");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 214, 22));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/gdexcel.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 1160, 140));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 120, 120));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbn/iconBack.png"))); // NOI18N
        btnBack.setText("Trở Về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 110, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Laydanhsach()
    {
         try {
            
            
            list= bnbus.Laydanhsachbenhnhan();
            
            DefaultTableModel model = (DefaultTableModel) grBenhNhan.getModel();
            
            for(int i=0;i<list.size();i++)
            {
                String LoaiThuoc = "";
                int SoLuong = 0;
                if (list.get(i).getDanhSachThuoc().size() != 0)
                {
                    for (THUOC t:list.get(i).getDanhSachThuoc())
                    {
                        LoaiThuoc +=  t.getMALOAITHUOC().replace(" ","") + ", ";
                        System.out.println(LoaiThuoc);
                        SoLuong += t.getSOLUONG();
                    }
                }
                // Xóa đi 2 kí tự dư cuối
            if (LoaiThuoc.length() > 0)
            {
                LoaiThuoc = LoaiThuoc.substring(0, LoaiThuoc.length() - 2);
            }
            model.addRow(new Object[]{list.get(i).getMABN(),list.get(i).getTENBN(),
                list.get(i).getTUOI(),list.get(i).getDIACHI(),list.get(i).getGIOITINH(),
                list.get(i).getLOAIBN(), list.get(i).getCANNANG(),LoaiThuoc, SoLuong});
            }
       
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Main_1 a = new Main_1();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new XuatExcel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JTable grBenhNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtPhanMem;
    // End of variables declaration//GEN-END:variables
}
